### ISSUE TITLE
Create new project crashes FEC

### ISSUE THREAD

**Issue by adriatic** [mattduffield/frontendcreator#32]
___Please note that I started this bug report from the state created to write the **[More questions on Use Entity section of the guide](https://github.com/mattduffield/frontendcreator/issues/31)**, so the crash could be a consequence of something that happened while I was making screenshots for that issue.___
***

Started the **[New Project Tutorial](https://mattduffield.gitbooks.io/frontend-creator/tutorials/manage-projects.html)**. Once I type in the name of this new project ("New Project"), I observed the following in the Chrome console:
```
A bad HTTP response code (404) was received when fetching the script.
/scripts/service-worker.js Failed to load resource: net::ERR_INVALID_RESPONSE
app-bundle-2f69f08739.js:3 currentRecord {fileType: "project", projectType: "aurelia-typescript", …}
59418231c2ef166dffd4847a.blob.core.windows.net/demo?restype=container&_=1521842179914:1 HEAD https://59418231c2ef166dffd4847a.blob.core.windows.net/demo?restype=container&_=1521842179914 404 (The specified container does not exist.)
app-bundle-2f69f08739.js:15 tree-node:setCurrentView {_id: {…}, userid: "59418231c2ef166dffd4847a", description: "This is a contact entity", fields: Array(6), …} true
app-bundle-2f69f08739.js:15 tree-node:setCurrentView {userid: "59418231c2ef166dffd4847a", …} true
app-bundle-2f69f08739.js:3 currentRecord {fileType: "project", projectType: "aurelia-typescript", …}
anchors.js:40 Unhandled rejection SyntaxError: Container name format is incorrect.
SyntaxError: Container name format is incorrect.
    at getNameError (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:9876:12)
    at ArgumentValidator.exports.containerNameIsValid (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:9894:19)
    at https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:11042:7
    at Object.validateArgs (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:10214:3)
    at BlobService.createContainerIfNotExists (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:11040:12)
    at https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:1:12153
    at i.t._execute (https://frontendcreator.com/app/scripts/vendor-bundle-60c0af5654.js:4:25669)
    at i._resolveFromExecutor (https://frontendcreator.com/app/scripts/vendor-bundle-60c0af5654.js:5:12732)
    at new i (https://frontendcreator.com/app/scripts/vendor-bundle-60c0af5654.js:5:4952)
    at e.createContainer (https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:1:12076)
    at e.newAureliaTypeScriptProject (https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:1:21520)
    at e.newProject (https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:1:17669)
    at e.saveProject (https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:3:21579)
    at e.save (https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:3:20652)
    at https://frontendcreator.com/app/scripts/app-bundle-2f69f08739.js:3:8700
    at n (https://frontendcreator.com/app/scripts/vendor-bundle-60c0af5654.js:10:9034)
R @ anchors.js:40
S @ converter.js:186
C @ converter.js:211
t._notifyUnhandledRejection @ helpers.js:38
(anonymous) @ options.js:135
setTimeout (async)
(anonymous) @ options.js:134
Promise.then (async)
r @ loader.js:17
u.hasDevTools.r.invokeLater @ options.js:133
t._ensurePossibleRejectionHandled @ helpers.js:18
i._reject @ stripLinkDefinitions.js:10
i._settlePromise @ spanGamut.js:2
i._settlePromise0 @ spanGamut.js:32
i._settlePromises @ stripLinkDefinitions.js:41
(anonymous) @ options.js:156
Promise.then (async)
r @ loader.js:17
u.hasDevTools.r.settlePromises @ options.js:155
i._reject @ stripLinkDefinitions.js:8
i._settlePromise @ spanGamut.js:2
i._settlePromiseCtx @ spanGamut.js:24
(anonymous) @ options.js:146
Promise.then (async)
r @ loader.js:17
u.hasDevTools.r.invoke @ options.js:145
i._then @ italicsAndBold.js:48
i.then @ images.js:7
e.newAureliaTypeScriptProject @ app-bundle-2f69f08739.js:1
e.newProject @ app-bundle-2f69f08739.js:1
e.saveProject @ app-bundle-2f69f08739.js:3
e.save @ app-bundle-2f69f08739.js:3
(anonymous) @ app-bundle-2f69f08739.js:3
n @ loader.js:17
e.publish @ loader.js:17
e.setFileName @ app-bundle-2f69f08739.js:11
t.evaluate @ loader.js:17
e.callSource @ loader.js:17
(anonymous) @ loader.js:17
te @ loader.js:17
```

___There is no Tutorial Project" in the projects Cache___

![image](https://user-images.githubusercontent.com/2712405/37869582-460136ec-2f90-11e8-8092-1b13330abfdc.png)

**Comment by adriatic** [comment]
Now, I started a fresh, by log-out, log-in seqence done first. The same claim remains - I cannot make a new project using the instructions from the guide's **[New Project Tutorial](https://mattduffield.gitbooks.io/frontend-creator/tutorials/manage-projects.html)**. Here is the content of the Chrome console, that appeared when I provided the project name:

![image](https://user-images.githubusercontent.com/2712405/37869654-eec95394-2f91-11e8-80e5-4f6edb3c2675.png)

```
currentRecord {fileType: "project", projectType: "aurelia-typescript", …}
anchors.js:40 Unhandled rejection SyntaxError: Container name format is incorrect.
SyntaxError: Container name format is incorrect.
    at getNameError (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:9876:12)
    at ArgumentValidator.exports.containerNameIsValid (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:9894:19)
    at https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:11042:7
    at Object.validateArgs (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:10214:3)
    at BlobService.createContainerIfNotExists (https://frontendcreator.com/app/scripts/azure-storage-blobonly.js:11040:12)
    at https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:1:8094
    at i.t._execute (https://frontendcreator.com/app/scripts/vendor-bundle-48a6658ea1.js:4:25645)
    at i._resolveFromExecutor (https://frontendcreator.com/app/scripts/vendor-bundle-48a6658ea1.js:5:12732)
    at new i (https://frontendcreator.com/app/scripts/vendor-bundle-48a6658ea1.js:5:4952)
    at e.createContainer (https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:1:8017)
    at e.newAureliaTypeScriptProject (https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:1:17461)
    at e.newProject (https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:1:13610)
    at e.saveProject (https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:3:19301)
    at e.save (https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:3:18374)
    at https://frontendcreator.com/app/scripts/app-bundle-844532ca3f.js:3:6422
    at n (https://frontendcreator.com/app/scripts/vendor-bundle-48a6658ea1.js:10:9034)
R @ anchors.js:40
S @ converter.js:186
C @ converter.js:211
t._notifyUnhandledRejection @ helpers.js:38
(anonymous) @ options.js:135
setTimeout (async)
(anonymous) @ options.js:134
Promise.then (async)
r @ loader.js:17
u.hasDevTools.r.invokeLater @ options.js:133
t._ensurePossibleRejectionHandled @ helpers.js:18
i._reject @ stripLinkDefinitions.js:10
i._settlePromise @ spanGamut.js:2
i._settlePromise0 @ spanGamut.js:32
i._settlePromises @ stripLinkDefinitions.js:41
(anonymous) @ options.js:156
Promise.then (async)
r @ loader.js:17
u.hasDevTools.r.settlePromises @ options.js:155
i._reject @ stripLinkDefinitions.js:8
i._settlePromise @ spanGamut.js:2
i._settlePromiseCtx @ spanGamut.js:24
(anonymous) @ options.js:146
Promise.then (async)
r @ loader.js:17
u.hasDevTools.r.invoke @ options.js:145
i._then @ italicsAndBold.js:48
i.then @ images.js:7
e.newAureliaTypeScriptProject @ app-bundle-844532ca3f.js:1
e.newProject @ app-bundle-844532ca3f.js:1
e.saveProject @ app-bundle-844532ca3f.js:3
e.save @ app-bundle-844532ca3f.js:3
(anonymous) @ app-bundle-844532ca3f.js:3
n @ loader.js:17
e.publish @ loader.js:17
e.setFileName @ app-bundle-844532ca3f.js:11
t.evaluate @ loader.js:17
e.callSource @ loader.js:17
(anonymous) @ loader.js:17
te @ loader.js:17
```
